### ISSUE TITLE
Edit Book Location

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project-bookshelves#31]
## Value Statement
As a user I want to be able to edit a book's location to either store unstored books or move already stored books.

## Acceptance criteria

- [x] Clicking on pencil icon on bookdetails opens shelfselector
- [x] Selecting a new location updates book location

## Complexity
M

## Tasks

- [x] Create branch 'feat-shelfLocationEdit'
- [x] Add icon to bookdetails
- [x] Add logic to edit shelfLocation
